INSERT INTO scholarship_accomplishment (id, created_by, created_date, updated_by, updated_date, operating_unit_type, amount, slots, total_obligation, obligation_rate, total_disbursement, disbursement_rate, enrolled, enrolled_utilization, graduates, graduates_utilization, assessed, assessed_utilization, certified, certified_utilization, employed, month, year, scholarship_type) VALUES (1, 'SYSTEM', now(), 'SYSTEM', now(), 'BILIRAN', 100, 100, 10, 100.00, 100, 100.00, 5, 50.00, 10, 20.00, 20, 20.00, 100, 100.00, 5, 'DECEMBER', 2020, 'TWSP');
INSERT INTO scholarship_accomplishment (id, created_by, created_date, updated_by, updated_date, operating_unit_type, amount, slots, total_obligation, obligation_rate, total_disbursement, disbursement_rate, enrolled, enrolled_utilization, graduates, graduates_utilization, assessed, assessed_utilization, certified, certified_utilization, employed, month, year, scholarship_type) VALUES (2, 'SYSTEM', now(), 'SYSTEM', now(), 'EASTERN_SAMAR', 100, 100, 10, 100.00, 100, 100.00, 5, 50.00, 10, 20.00, 20, 20.00, 100, 100.00, 5, 'DECEMBER', 2020, 'TWSP');
INSERT INTO scholarship_accomplishment (id, created_by, created_date, updated_by, updated_date, operating_unit_type, amount, slots, total_obligation, obligation_rate, total_disbursement, disbursement_rate, enrolled, enrolled_utilization, graduates, graduates_utilization, assessed, assessed_utilization, certified, certified_utilization, employed, month, year, scholarship_type) VALUES (3, 'SYSTEM', now(), 'SYSTEM', now(), 'LEYTE', 100, 100, 10, 100.00, 100, 100.00, 5, 50.00, 10, 20.00, 20, 20.00, 100, 100.00, 5, 'DECEMBER', 2020, 'TWSP');
INSERT INTO scholarship_accomplishment (id, created_by, created_date, updated_by, updated_date, operating_unit_type, amount, slots, total_obligation, obligation_rate, total_disbursement, disbursement_rate, enrolled, enrolled_utilization, graduates, graduates_utilization, assessed, assessed_utilization, certified, certified_utilization, employed, month, year, scholarship_type) VALUES (4, 'SYSTEM', now(), 'SYSTEM', now(), 'NORTHERN_SAMAR', 100, 100, 10, 100.00, 100, 100.00, 5, 50.00, 10, 20.00, 20, 20.00, 100, 100.00, 5, 'DECEMBER', 2020, 'TWSP');
INSERT INTO scholarship_accomplishment (id, created_by, created_date, updated_by, updated_date, operating_unit_type, amount, slots, total_obligation, obligation_rate, total_disbursement, disbursement_rate, enrolled, enrolled_utilization, graduates, graduates_utilization, assessed, assessed_utilization, certified, certified_utilization, employed, month, year, scholarship_type) VALUES (5, 'SYSTEM', now(), 'SYSTEM', now(), 'SAMAR', 100, 100, 10, 100.00, 100, 100.00, 5, 50.00, 10, 20.00, 20, 20.00, 100, 100.00, 5, 'DECEMBER', 2020, 'TWSP');
INSERT INTO scholarship_accomplishment (id, created_by, created_date, updated_by, updated_date, operating_unit_type, amount, slots, total_obligation, obligation_rate, total_disbursement, disbursement_rate, enrolled, enrolled_utilization, graduates, graduates_utilization, assessed, assessed_utilization, certified, certified_utilization, employed, month, year, scholarship_type) VALUES (6, 'SYSTEM', now(), 'SYSTEM', now(), 'SOUTHERN_LEYTE', 100, 100, 10, 100.00, 100, 100.00, 5, 50.00, 10, 20.00, 20, 20.00, 100, 100.00, 5, 'DECEMBER', 2020, 'TWSP');

INSERT INTO scholarship_accomplishment (id, created_by, created_date, updated_by, updated_date, operating_unit_type, amount, slots, total_obligation, obligation_rate, total_disbursement, disbursement_rate, enrolled, enrolled_utilization, graduates, graduates_utilization, assessed, assessed_utilization, certified, certified_utilization, employed, month, year, scholarship_type) VALUES (7, 'SYSTEM', now(), 'SYSTEM', now(), 'BILIRAN', 100, 100, 10, 100.00, 100, 100.00, 5, 50.00, 10, 20.00, 20, 20.00, 100, 100.00, 5, 'DECEMBER', 2020, 'PESFA');
INSERT INTO scholarship_accomplishment (id, created_by, created_date, updated_by, updated_date, operating_unit_type, amount, slots, total_obligation, obligation_rate, total_disbursement, disbursement_rate, enrolled, enrolled_utilization, graduates, graduates_utilization, assessed, assessed_utilization, certified, certified_utilization, employed, month, year, scholarship_type) VALUES (8, 'SYSTEM', now(), 'SYSTEM', now(), 'EASTERN_SAMAR', 100, 100, 10, 100.00, 100, 100.00, 5, 50.00, 10, 20.00, 20, 20.00, 100, 100.00, 5, 'DECEMBER', 2020, 'PESFA');
INSERT INTO scholarship_accomplishment (id, created_by, created_date, updated_by, updated_date, operating_unit_type, amount, slots, total_obligation, obligation_rate, total_disbursement, disbursement_rate, enrolled, enrolled_utilization, graduates, graduates_utilization, assessed, assessed_utilization, certified, certified_utilization, employed, month, year, scholarship_type) VALUES (9, 'SYSTEM', now(), 'SYSTEM', now(), 'LEYTE', 100, 100, 10, 100.00, 100, 100.00, 5, 50.00, 10, 20.00, 20, 20.00, 100, 100.00, 5, 'DECEMBER', 2020, 'PESFA');
INSERT INTO scholarship_accomplishment (id, created_by, created_date, updated_by, updated_date, operating_unit_type, amount, slots, total_obligation, obligation_rate, total_disbursement, disbursement_rate, enrolled, enrolled_utilization, graduates, graduates_utilization, assessed, assessed_utilization, certified, certified_utilization, employed, month, year, scholarship_type) VALUES (10, 'SYSTEM', now(), 'SYSTEM', now(), 'NORTHERN_SAMAR', 100, 100, 10, 100.00, 100, 100.00, 5, 50.00, 10, 20.00, 20, 20.00, 100, 100.00, 5, 'DECEMBER', 2020, 'PESFA');
INSERT INTO scholarship_accomplishment (id, created_by, created_date, updated_by, updated_date, operating_unit_type, amount, slots, total_obligation, obligation_rate, total_disbursement, disbursement_rate, enrolled, enrolled_utilization, graduates, graduates_utilization, assessed, assessed_utilization, certified, certified_utilization, employed, month, year, scholarship_type) VALUES (11, 'SYSTEM', now(), 'SYSTEM', now(), 'SAMAR', 100, 100, 10, 100.00, 100, 100.00, 5, 50.00, 10, 20.00, 20, 20.00, 100, 100.00, 5, 'DECEMBER', 2020, 'PESFA');
INSERT INTO scholarship_accomplishment (id, created_by, created_date, updated_by, updated_date, operating_unit_type, amount, slots, total_obligation, obligation_rate, total_disbursement, disbursement_rate, enrolled, enrolled_utilization, graduates, graduates_utilization, assessed, assessed_utilization, certified, certified_utilization, employed, month, year, scholarship_type) VALUES (12, 'SYSTEM', now(), 'SYSTEM', now(), 'SOUTHERN_LEYTE', 100, 100, 10, 100.00, 100, 100.00, 5, 50.00, 10, 20.00, 20, 20.00, 100, 100.00, 5, 'DECEMBER', 2020, 'PESFA');


INSERT INTO scholarship_accomplishment (id, created_by, created_date, updated_by, updated_date, operating_unit_type, amount, slots, total_obligation, obligation_rate, total_disbursement, disbursement_rate, enrolled, enrolled_utilization, graduates, graduates_utilization, assessed, assessed_utilization, certified, certified_utilization, employed, month, year, scholarship_type) VALUES (13, 'SYSTEM', now(), 'SYSTEM', now(), 'BILIRAN', 100, 100, 10, 100.00, 100, 100.00, 5, 50.00, 10, 20.00, 20, 20.00, 100, 100.00, 5, 'NOVEMBER', 2020, 'PESFA');
INSERT INTO scholarship_accomplishment (id, created_by, created_date, updated_by, updated_date, operating_unit_type, amount, slots, total_obligation, obligation_rate, total_disbursement, disbursement_rate, enrolled, enrolled_utilization, graduates, graduates_utilization, assessed, assessed_utilization, certified, certified_utilization, employed, month, year, scholarship_type) VALUES (14, 'SYSTEM', now(), 'SYSTEM', now(), 'EASTERN_SAMAR', 100, 100, 10, 100.00, 100, 100.00, 5, 50.00, 10, 20.00, 20, 20.00, 100, 100.00, 5, 'NOVEMBER', 2020, 'PESFA');
INSERT INTO scholarship_accomplishment (id, created_by, created_date, updated_by, updated_date, operating_unit_type, amount, slots, total_obligation, obligation_rate, total_disbursement, disbursement_rate, enrolled, enrolled_utilization, graduates, graduates_utilization, assessed, assessed_utilization, certified, certified_utilization, employed, month, year, scholarship_type) VALUES (15, 'SYSTEM', now(), 'SYSTEM', now(), 'LEYTE', 100, 100, 10, 100.00, 100, 100.00, 5, 50.00, 10, 20.00, 20, 20.00, 100, 100.00, 5, 'NOVEMBER', 2020, 'PESFA');
INSERT INTO scholarship_accomplishment (id, created_by, created_date, updated_by, updated_date, operating_unit_type, amount, slots, total_obligation, obligation_rate, total_disbursement, disbursement_rate, enrolled, enrolled_utilization, graduates, graduates_utilization, assessed, assessed_utilization, certified, certified_utilization, employed, month, year, scholarship_type) VALUES (16, 'SYSTEM', now(), 'SYSTEM', now(), 'NORTHERN_SAMAR', 100, 100, 10, 100.00, 100, 100.00, 5, 50.00, 10, 20.00, 20, 20.00, 100, 100.00, 5, 'NOVEMBER', 2020, 'PESFA');
INSERT INTO scholarship_accomplishment (id, created_by, created_date, updated_by, updated_date, operating_unit_type, amount, slots, total_obligation, obligation_rate, total_disbursement, disbursement_rate, enrolled, enrolled_utilization, graduates, graduates_utilization, assessed, assessed_utilization, certified, certified_utilization, employed, month, year, scholarship_type) VALUES (17, 'SYSTEM', now(), 'SYSTEM', now(), 'SAMAR', 100, 100, 10, 100.00, 100, 100.00, 5, 50.00, 10, 20.00, 20, 20.00, 100, 100.00, 5, 'NOVEMBER', 2020, 'PESFA');
INSERT INTO scholarship_accomplishment (id, created_by, created_date, updated_by, updated_date, operating_unit_type, amount, slots, total_obligation, obligation_rate, total_disbursement, disbursement_rate, enrolled, enrolled_utilization, graduates, graduates_utilization, assessed, assessed_utilization, certified, certified_utilization, employed, month, year, scholarship_type) VALUES (18, 'SYSTEM', now(), 'SYSTEM', now(), 'SOUTHERN_LEYTE', 100, 100, 10, 100.00, 100, 100.00, 5, 50.00, 10, 20.00, 20, 20.00, 100, 100.00, 5, 'NOVEMBER', 2020, 'PESFA');



INSERT INTO scholarship_accomplishment (id, created_by, created_date, updated_by, updated_date, operating_unit_type, amount, slots, total_obligation, obligation_rate, total_disbursement, disbursement_rate, enrolled, enrolled_utilization, graduates, graduates_utilization, assessed, assessed_utilization, certified, certified_utilization, employed, month, year, scholarship_type) VALUES (19, 'SYSTEM', now(), 'SYSTEM', now(), 'BILIRAN', 100, 100, 10, 100.00, 100, 100.00, 5, 50.00, 10, 20.00, 20, 20.00, 100, 100.00, 5, 'JANUARY', 2021, 'PESFA');
INSERT INTO scholarship_accomplishment (id, created_by, created_date, updated_by, updated_date, operating_unit_type, amount, slots, total_obligation, obligation_rate, total_disbursement, disbursement_rate, enrolled, enrolled_utilization, graduates, graduates_utilization, assessed, assessed_utilization, certified, certified_utilization, employed, month, year, scholarship_type) VALUES (20, 'SYSTEM', now(), 'SYSTEM', now(), 'EASTERN_SAMAR', 100, 100, 10, 100.00, 100, 100.00, 5, 50.00, 10, 20.00, 20, 20.00, 100, 100.00, 5, 'JANUARY', 2021, 'PESFA');
INSERT INTO scholarship_accomplishment (id, created_by, created_date, updated_by, updated_date, operating_unit_type, amount, slots, total_obligation, obligation_rate, total_disbursement, disbursement_rate, enrolled, enrolled_utilization, graduates, graduates_utilization, assessed, assessed_utilization, certified, certified_utilization, employed, month, year, scholarship_type) VALUES (21, 'SYSTEM', now(), 'SYSTEM', now(), 'LEYTE', 100, 100, 10, 100.00, 100, 100.00, 5, 50.00, 10, 20.00, 20, 20.00, 100, 100.00, 5, 'JANUARY', 2021, 'PESFA');
INSERT INTO scholarship_accomplishment (id, created_by, created_date, updated_by, updated_date, operating_unit_type, amount, slots, total_obligation, obligation_rate, total_disbursement, disbursement_rate, enrolled, enrolled_utilization, graduates, graduates_utilization, assessed, assessed_utilization, certified, certified_utilization, employed, month, year, scholarship_type) VALUES (22, 'SYSTEM', now(), 'SYSTEM', now(), 'NORTHERN_SAMAR', 100, 100, 10, 100.00, 100, 100.00, 5, 50.00, 10, 20.00, 20, 20.00, 100, 100.00, 5, 'JANUARY', 2021, 'PESFA');
INSERT INTO scholarship_accomplishment (id, created_by, created_date, updated_by, updated_date, operating_unit_type, amount, slots, total_obligation, obligation_rate, total_disbursement, disbursement_rate, enrolled, enrolled_utilization, graduates, graduates_utilization, assessed, assessed_utilization, certified, certified_utilization, employed, month, year, scholarship_type) VALUES (23, 'SYSTEM', now(), 'SYSTEM', now(), 'SAMAR', 100, 100, 10, 100.00, 100, 100.00, 5, 50.00, 10, 20.00, 20, 20.00, 100, 100.00, 5, 'JANUARY', 2021, 'PESFA');
INSERT INTO scholarship_accomplishment (id, created_by, created_date, updated_by, updated_date, operating_unit_type, amount, slots, total_obligation, obligation_rate, total_disbursement, disbursement_rate, enrolled, enrolled_utilization, graduates, graduates_utilization, assessed, assessed_utilization, certified, certified_utilization, employed, month, year, scholarship_type) VALUES (24, 'SYSTEM', now(), 'SYSTEM', now(), 'SOUTHERN_LEYTE', 100, 100, 10, 100.00, 100, 100.00, 5, 50.00, 10, 20.00, 20, 20.00, 100, 100.00, 5, 'JANUARY', 2021, 'PESFA');